# Site settings
author: Pierre 
title: A Coding Journey 
header-img: img/home-bg.png
email: plarmony24@gmail.com
copyright_name: Pierre 
description: > # this means to ignore newlines until "baseurl:"
  codemap to success
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  PEL23

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
